services:
  # === Frontend ===
  frontend:
    image: httpd:latest
    container_name: frontend
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    networks:
      - frontend
    depends_on:
      - backend

  # === Backend ===
  backend:
    build: ./backend
    image: kamalsabry/backend-app:1.0
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_NAME=mydb
    networks:
      - frontend
      - backend
    depends_on:
      - database

  # === Database ===
  database:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root123
      - MARIADB_DATABASE=mydb
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# === Networks ===
networks:
  frontend:
    name: frontend_network
  backend:
    name: backend_network

# === Volumes ===
volumes:
  db_data:

